spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 'bb3d6f2322597f3a79205c02f79d56ec'
custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUserOauthId: 'oauthId'
